fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin/

bacon_language:
    resource: "@BaconLanguageBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin

app_site:
    resource: "@AppBundle/Controller/Site"
    type:     annotation