_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

a2_c_language:
    resource: "@A2CLanguageBundle/Controller/"
    type:     annotation
    prefix:   /

a2_c_dashboard:
    resource: "@A2CDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin/


a2_c_core:
    resource: "@A2CCoreBundle/Controller/"
    type:     annotation

a2_c_user:
    resource: "@A2CUserBundle/Controller/"
    type: annotation