fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin/

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group

bacon_acl_module:
    resource: "@BaconAclBundle/Controller/"
    type:     annotation
    prefix:   /admin/

bacon_language:
    resource: "@BaconLanguageBundle/Controller/"
    type:     annotation
    prefix:   /admin

app_site:
    resource: "@AppBundle/Controller/Site"
    type:     annotation

app_backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation
    prefix:   /admin

bacon_user:
    resource: "@BaconUserBundle/Controller/"
    type:     annotation
    prefix:   /admin
