fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin/

bacon_language:
    resource: "@BaconLanguageBundle/Controller/"
    type:     annotation
    prefix:   /admin

app_site:
    resource: "@AppBundle/Controller/Site"
    type:     annotation

app_backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation
    prefix:   "/admin"