# app/config/security.yml
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        null
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        db:
            id: uecode.api_key.provider.user_provider

    firewalls:
        admin:
            pattern: /admin(.*)
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: admin_default_route
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
        api:
            pattern: ^/api/*
            api_key: true
            stateless: true
            provider: db # Required if you have multiple providers and firewalls

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
