# Servidor de homologacao
homolog:
  host: localhost 
  port: 80 
  user:
  password:
  stage: homologacao
  deploy_path: /var/www/test

# Servidor de produção 01
production:
  host: localhost
  port: 80
  user:
  password:
  stage: producao
  deploy_path: /var/www/test

