knp_gaufrette:
    stream_wrapper: ~
    adapters:
        language:
            local:
                directory: %kernel.root_dir%/../web/uploads/language
                create: true
    filesystems:
        language:
            adapter: language
            alias: language_filesystem